# Generated by Django 4.2.3 on 2023-09-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Blog.blog'),
        ),
    ]
