# Generated by Django 4.2.3 on 2023-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_comment_user_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comm',
            field=models.CharField(max_length=500),
        ),
    ]
